name: genv
dependencies:
- bkcharts=0.2=py36_0
- bokeh=0.12.6=py36_0
- jinja2=2.9.6=py36_0
- markupsafe=0.23=py36_2
- mkl=2017.0.3=0
- numpy=1.13.1=py36_0
- openssl=1.0.2l=0
- pip=9.0.1=py36_1
- python=3.6.1=2
- python-dateutil=2.6.0=py36_0
- pyyaml=3.12=py36_0
- readline=6.2=2
- requests=2.14.2=py36_0
- setuptools=27.2.0=py36_0
- six=1.10.0=py36_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- tornado=4.5.1=py36_0
- wheel=0.29.0=py36_0
- xz=5.2.2=1
- yaml=0.1.6=0
- zlib=1.2.8=3
- pip:
  - appnope==0.1.0
  - decorator==4.0.11
  - ipython==6.1.0
  - ipython-genutils==0.2.0
  - jedi==0.10.2
  - pexpect==4.2.1
  - pickleshare==0.7.4
  - prompt-toolkit==1.0.14
  - ptyprocess==0.5.2
  - pygments==2.2.0
  - simplegeneric==0.8.1
  - traitlets==4.3.2
  - wcwidth==0.1.7

